EESS_MICRORED = ['ARANJUEZ','CLUB DE LEONES','DE ESPECIALIDADES BASICAS LA NORIA','EL BOSQUE','LA UNION','LIBERTAD',
     'LOS GRANADOS "SAGRADO CORAZON"','LOS JARDINES','PESQUEDA II','PESQUEDA III','SAN MARTIN DE PORRES'
]